# Reference Database API

FROM python:3.10.11-slim-buster

WORKDIR /app

COPY . .

RUN pip install .

EXPOSE 8001

ENV host_address="0.0.0.0"

ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG DATABASE_SSL_MODE

ENV DB_HOST $DATABASE_HOST
ENV DB_NAME $DATABASE_NAME
ENV DB_USER $DATABASE_USER
ENV DB_PASSWORD $DATABASE_PASSWORD
ENV DB_PORT $DATABASE_PORT
ENV DB_SSL_MODE $DATABASE_SSL_MODE

CMD ["python", "-m", "reference_database_api_deployment.main"]
